### ISSUE TITLE
Installing package downgraded plotly to earlier version, causing conflicts

### ISSUE THREAD

**Issue by iadjali** [meffmadd/pandas-visual-analysis#2]
Hi, this seems like an awesome package. I installed it earlier today but it downgraded plotly from the (current version) 4.10 to version 4.9. Unfortunately this has caused quite a few conflicts with some of my python projects involving plotly. Are there any plans to release a version working with plotly 4.10.0?
Thanks.

**Comment by meffmadd** [comment]
Thank you very much! That is pretty strange since version 0.0.3 has a dependency on plotly>=4.9.0 so it should also work with 4.10.0 and particularly it should not downgrade it. 

However, I was planning to release version 0.0.4 anyway, which depends on plotly>=4.10.0 so this should work for you. I will try to release it today! In the meantime you could manually upgrade plotly back to 4.10.0.

**Comment by iadjali** [comment]
Thanks for the quick reply, yes I upgraded manually back to 4.10.0 and so far it seems to be working so no real issue in the end.
Great work and looks cool, nothing quite like it, it's likely to become a popular package!

**Comment by meffmadd** [comment]
Nothing major had to be done and version 0.0.4 was successfully released, which comes with a lot of upgrades! Install it with `pip install -I pandas-visual-analysis==0.0.4`.

**Comment by meffmadd** [comment]
> Great work and looks cool, nothing quite like it, it's likely to become a popular package!

Again, thanks and let's hope it does! 😁
