### ISSUE TITLE
"Extension host terminated unexpectedly" in VS Code 

### ISSUE THREAD

**Issue by skuzzard** [meffmadd/pandas-visual-analysis#21]
Hello @meffmadd! 

While implementing your code in Visual Studio Code, I break the application, which freezes after getting the error "Extension host terminated unexpectedly." This happens after trying to adjust the dimension order in a parallel coordinates plot. 
For example, using the following code:
```

import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv"

df = pd.read_csv(url)

from pandas_visual_analysis import VisualAnalysis, DataSource

data = DataSource(df)
VisualAnalysis(data, layout=[['ParallelCoordinates', 'Scatter']])
```

Then, trying to slide a dimension axis within the parallel coordinates plot, I get the terminated extension host failure and am forced to restart VS Code. For what it's worth, I do not experience this same failure when implementing a parallel coordinates plot directly using plotly.

**Comment by meffmadd** [comment]
Hi @skuzzard! Thanks for using pandas-visual-analysis!

I tried to execute the code on my machine in VS Code and I had no problems. This problem seems to be related to Visual Studio Code (for example: https://github.com/microsoft/vscode-python/issues/342). I would suggest installing the latest versions and making sure that VS Code has enough resources to run.
